# Generated by Django 5.2.3 on 2025-07-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
    ]
